# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Zouqiba' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.0'
  pod 'Fabric'
  pod 'Digits'
  pod 'Crashlytics'
  pod 'TwitterCore' 
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'Kanna'
  pod 'CHRTextFieldFormatter'
  pod 'ImagePicker'
  pod 'JGProgressHUD'

# Pods for Zouqiba

  target 'ZouqibaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZouqibaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
